#!/usr/bin/env python3
"""Install the canonical make-ppt Agent Skill into supported AI clients."""

from __future__ import annotations

import argparse
import json
import shutil
from pathlib import Path


CLIENTS = ("codex", "claude", "kiro", "copilot")
AGENT_ROLE_SPECS = {
    "ppt-planner": "ppt-planner-role.md",
    "ppt-builder": "ppt-builder-role.md",
}
AGENT_DESCRIPTIONS = {
    "ppt-planner": "Plan new make-ppt presentations from source evidence and write presentation/outline.md.",
    "ppt-builder": "Implement an approved make-ppt outline as an editable PPTX and perform visual QA.",
}
GENERATED_MARKER = (
    "Generated by make-ppt/install.py. "
    "Edit the canonical role or client integration template, then reinstall."
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Install make-ppt into Agent Skills compatible AI clients."
    )
    parser.add_argument(
        "--client",
        choices=(*CLIENTS, "all"),
        default="all",
        help="Client to install for (default: all).",
    )
    parser.add_argument(
        "--scope",
        choices=("user", "project"),
        default="user",
        help="Install globally for the user or into one project (default: user).",
    )
    parser.add_argument(
        "--project-dir",
        type=Path,
        default=Path.cwd(),
        help="Project root for --scope project (default: current directory).",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Replace an existing make-ppt installation.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print target paths without writing files.",
    )
    return parser.parse_args()


def user_target(client: str) -> Path:
    roots = {
        "codex": Path.home() / ".agents" / "skills",
        "claude": Path.home() / ".claude" / "skills",
        "kiro": Path.home() / ".kiro" / "skills",
        "copilot": Path.home() / ".copilot" / "skills",
    }
    return roots[client] / "make-ppt"


def project_target(client: str, project_dir: Path) -> Path:
    roots = {
        "codex": project_dir / ".agents" / "skills",
        "claude": project_dir / ".claude" / "skills",
        "kiro": project_dir / ".kiro" / "skills",
        "copilot": project_dir / ".github" / "skills",
    }
    return roots[client] / "make-ppt"


def agents_dir(client: str, scope: str, project_dir: Path) -> Path:
    if scope == "user":
        roots = {
            "codex": Path.home() / ".codex" / "agents",
            "claude": Path.home() / ".claude" / "agents",
            "kiro": Path.home() / ".kiro" / "agents",
            "copilot": Path.home() / ".copilot" / "agents",
        }
    else:
        roots = {
            "codex": project_dir / ".codex" / "agents",
            "claude": project_dir / ".claude" / "agents",
            "kiro": project_dir / ".kiro" / "agents",
            "copilot": project_dir / ".github" / "agents",
        }
    return roots[client]


def safe_to_replace(target: Path) -> bool:
    return target.name == "make-ppt" and target.parent.name == "skills"


def render_markdown_agent(frontmatter: Path, role: Path) -> str:
    frontmatter_text = frontmatter.read_text(encoding="utf-8").strip()
    role_text = role.read_text(encoding="utf-8").strip()
    if frontmatter_text.startswith("---") or frontmatter_text.endswith("---"):
        raise ValueError(
            f"Agent frontmatter template must not include delimiters: {frontmatter}"
        )
    return (
        f"---\n{frontmatter_text}\n---\n\n"
        f"<!-- {GENERATED_MARKER} -->\n\n{role_text}\n"
    )


def write_text_atomic(target: Path, content: str) -> None:
    target.parent.mkdir(parents=True, exist_ok=True)
    temporary = target.with_name(f".{target.name}.tmp")
    try:
        temporary.write_text(content, encoding="utf-8", newline="\n")
        temporary.replace(target)
    finally:
        if temporary.exists():
            temporary.unlink()


def render_codex_agent(agent_name: str, role: Path) -> str:
    role_text = role.read_text(encoding="utf-8").strip()
    description = AGENT_DESCRIPTIONS[agent_name]
    return (
        f"# {GENERATED_MARKER}\n"
        f"name = {json.dumps(agent_name)}\n"
        f"description = {json.dumps(description, ensure_ascii=False)}\n"
        f"developer_instructions = {json.dumps(role_text, ensure_ascii=False)}\n"
    )


def agent_file_name(client: str, agent_name: str) -> str:
    suffix = {
        "codex": ".toml",
        "claude": ".md",
        "kiro": ".md",
        "copilot": ".agent.md",
    }[client]
    return f"{agent_name}{suffix}"


def sync_agents(
    client: str,
    skill_source: Path,
    integrations_dir: Path,
    target_dir: Path,
    *,
    dry_run: bool,
) -> None:
    for agent_name, role_name in AGENT_ROLE_SPECS.items():
        target = target_dir / agent_file_name(client, agent_name)
        print(f"{client}-agent -> {target}")
        if dry_run:
            continue

        role = skill_source / "references" / role_name
        if not role.is_file():
            raise FileNotFoundError(f"Canonical role not found: {role}")

        if client == "codex":
            content = render_codex_agent(agent_name, role)
        else:
            frontmatter = integrations_dir / client / f"{agent_name}.yaml"
            if not frontmatter.is_file():
                raise FileNotFoundError(
                    f"{client} agent template not found: {frontmatter}"
                )
            content = render_markdown_agent(frontmatter, role)
        write_text_atomic(target, content)


def install_one(
    client: str,
    source: Path,
    codex_metadata: Path,
    target: Path,
    *,
    force: bool,
    dry_run: bool,
) -> None:
    print(f"{client:7} -> {target}")
    if dry_run:
        return

    if target.exists() or target.is_symlink():
        if not force:
            raise FileExistsError(
                f"{target} already exists; rerun with --force to replace it."
            )
        if not safe_to_replace(target):
            raise RuntimeError(f"Refusing to replace unexpected target: {target}")
        if target.is_dir() and not target.is_symlink():
            shutil.rmtree(target)
        else:
            target.unlink()

    target.parent.mkdir(parents=True, exist_ok=True)
    shutil.copytree(
        source,
        target,
        ignore=shutil.ignore_patterns("__pycache__", "*.pyc", ".DS_Store"),
    )

    if client == "codex" and codex_metadata.exists():
        metadata_target = target / "agents" / "openai.yaml"
        metadata_target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(codex_metadata, metadata_target)


def main() -> int:
    args = parse_args()
    repo_dir = Path(__file__).resolve().parent
    source = repo_dir / "skill" / "make-ppt"
    codex_metadata = repo_dir / "integrations" / "codex" / "openai.yaml"
    integrations_dir = repo_dir / "integrations"

    if not (source / "SKILL.md").is_file():
        raise FileNotFoundError(f"Canonical skill not found: {source}")

    clients = CLIENTS if args.client == "all" else (args.client,)
    project_dir = args.project_dir.resolve()

    jobs = []
    for client in clients:
        target = (
            user_target(client)
            if args.scope == "user"
            else project_target(client, project_dir)
        )
        jobs.append((client, target))

    existing = [
        target for _, target in jobs if target.exists() or target.is_symlink()
    ]
    if existing and not args.force and not args.dry_run:
        formatted = "\n".join(f"  - {target}" for target in existing)
        raise FileExistsError(
            "Installation stopped before making changes because these targets exist:\n"
            f"{formatted}\nRerun with --force to replace them."
        )

    for client, target in jobs:
        install_one(
            client,
            source,
            codex_metadata,
            target,
            force=args.force,
            dry_run=args.dry_run,
        )
        sync_agents(
            client,
            source,
            integrations_dir,
            agents_dir(client, args.scope, project_dir),
            dry_run=args.dry_run,
        )

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
