#!/usr/bin/env python3
"""Install the canonical make-ppt Agent Skill into supported AI clients."""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from datetime import datetime
from pathlib import Path

from client_registry import (
    ClientSpec,
    agent_target,
    legacy_skill_targets,
    load_registry,
    skill_target,
)


AGENT_ROLE_SPECS = {
    "ppt-planner": "ppt-planner-role.md",
    "ppt-builder": "ppt-builder-role.md",
}
AGENT_DESCRIPTIONS = {
    "ppt-planner": "Compare narrative directions or write an approved-direction outline from source evidence for make-ppt presentations.",
    "ppt-builder": "Implement an approved make-ppt outline as an editable PPTX and perform visual QA.",
}
GENERATED_MARKER = (
    "Generated by make-ppt/install.py. "
    "Edit the canonical role or client integration template, then reinstall."
)


def parse_args(registry: dict[str, ClientSpec]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Install make-ppt into Agent Skills compatible AI clients."
    )
    parser.add_argument(
        "--client",
        choices=(*registry, "all"),
        default="all",
        help="Client to install for (default: all registered clients).",
    )
    parser.add_argument(
        "--scope",
        choices=("user", "project"),
        default="user",
        help="Install globally for the user or into one project (default: user).",
    )
    parser.add_argument(
        "--project-dir",
        type=Path,
        default=Path.cwd(),
        help="Project root for --scope project (default: current directory).",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Replace an existing make-ppt installation.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print target paths without writing files.",
    )
    parser.add_argument(
        "--migrate-legacy",
        action="store_true",
        help="Move registered legacy installations to timestamped backups after installing.",
    )
    parser.add_argument(
        "--install-python-deps",
        action="store_true",
        help="Install the bundled Python requirements with the active interpreter.",
    )
    return parser.parse_args()


def safe_skill_target(target: Path) -> bool:
    resolved = target.resolve()
    return resolved.name == "make-ppt" and resolved.parent.name == "skills"


def render_markdown_agent(frontmatter: Path, role: Path) -> str:
    frontmatter_text = frontmatter.read_text(encoding="utf-8").strip()
    role_text = role.read_text(encoding="utf-8").strip()
    if frontmatter_text.startswith("---") or frontmatter_text.endswith("---"):
        raise ValueError(
            f"Agent frontmatter template must not include delimiters: {frontmatter}"
        )
    return (
        f"---\n{frontmatter_text}\n---\n\n"
        f"<!-- {GENERATED_MARKER} -->\n\n{role_text}\n"
    )


def write_text_atomic(target: Path, content: str) -> None:
    target.parent.mkdir(parents=True, exist_ok=True)
    temporary = target.with_name(f".{target.name}.tmp")
    try:
        temporary.write_text(content, encoding="utf-8", newline="\n")
        temporary.replace(target)
    finally:
        if temporary.exists():
            temporary.unlink()


def render_codex_agent(agent_name: str, role: Path) -> str:
    role_text = role.read_text(encoding="utf-8").strip()
    description = AGENT_DESCRIPTIONS[agent_name]
    return (
        f"# {GENERATED_MARKER}\n"
        f"name = {json.dumps(agent_name)}\n"
        f"description = {json.dumps(description, ensure_ascii=False)}\n"
        f"developer_instructions = {json.dumps(role_text, ensure_ascii=False)}\n"
    )


def sync_agents(
    spec: ClientSpec,
    skill_source: Path,
    integrations_dir: Path,
    scope: str,
    project_dir: Path,
    *,
    dry_run: bool,
) -> None:
    for agent_name, role_name in AGENT_ROLE_SPECS.items():
        target = agent_target(spec, agent_name, scope, project_dir)
        print(f"{spec.client_id}-agent -> {target}")
        if dry_run:
            continue

        role = skill_source / "references" / role_name
        if not role.is_file():
            raise FileNotFoundError(f"Canonical role not found: {role}")

        if spec.agent_format == "codex-toml":
            content = render_codex_agent(agent_name, role)
        else:
            frontmatter = (
                integrations_dir / spec.integration_dir / f"{agent_name}.yaml"
            )
            if not frontmatter.is_file():
                raise FileNotFoundError(
                    f"{spec.client_id} agent template not found: {frontmatter}"
                )
            content = render_markdown_agent(frontmatter, role)
        write_text_atomic(target, content)


def install_skill(
    source: Path,
    target: Path,
    *,
    force: bool,
    dry_run: bool,
) -> None:
    if dry_run:
        return
    if target.exists() or target.is_symlink():
        if not force:
            raise FileExistsError(
                f"{target} already exists; rerun with --force to replace it."
            )
        if not safe_skill_target(target):
            raise RuntimeError(f"Refusing to replace unexpected target: {target}")
        if target.is_dir() and not target.is_symlink():
            shutil.rmtree(target)
        else:
            target.unlink()

    target.parent.mkdir(parents=True, exist_ok=True)
    shutil.copytree(
        source,
        target,
        ignore=shutil.ignore_patterns("__pycache__", "*.pyc", ".DS_Store"),
    )


def apply_skill_metadata(
    spec: ClientSpec,
    integrations_dir: Path,
    target: Path,
    *,
    dry_run: bool,
) -> None:
    if not spec.skill_metadata:
        return
    source = integrations_dir / spec.skill_metadata["source"]
    destination = target / spec.skill_metadata["target"]
    print(f"{spec.client_id}-metadata -> {destination}")
    if dry_run:
        return
    if not source.is_file():
        raise FileNotFoundError(f"Client skill metadata not found: {source}")
    destination.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(source, destination)


def backup_target(path: Path) -> Path:
    stamp = datetime.now().strftime("%Y%m%d%H%M%S")
    candidate = path.with_name(f"{path.name}.legacy-{stamp}")
    sequence = 1
    while candidate.exists():
        candidate = path.with_name(f"{path.name}.legacy-{stamp}-{sequence}")
        sequence += 1
    return candidate


def handle_legacy_installations(
    specs: tuple[ClientSpec, ...],
    scope: str,
    project_dir: Path,
    *,
    migrate: bool,
    dry_run: bool,
) -> None:
    seen: set[Path] = set()
    for spec in specs:
        for legacy in legacy_skill_targets(spec, scope, project_dir):
            resolved = legacy.resolve()
            if resolved in seen or not (legacy.exists() or legacy.is_symlink()):
                continue
            seen.add(resolved)
            if not safe_skill_target(legacy):
                raise RuntimeError(f"Refusing to migrate unexpected target: {legacy}")
            if not migrate:
                print(
                    f"WARNING: {spec.client_id} legacy skill found at {legacy}; "
                    "rerun with --migrate-legacy to move it to a timestamped backup."
                )
                continue
            backup = backup_target(legacy)
            print(f"{spec.client_id}-legacy -> {backup}")
            if not dry_run:
                shutil.move(str(legacy), str(backup))


def install_python_dependencies(requirements: Path, *, dry_run: bool) -> None:
    command = [sys.executable, "-m", "pip", "install", "-r", str(requirements)]
    print("python-deps -> " + " ".join(command))
    if not dry_run:
        subprocess.run(command, check=True)


def main() -> int:
    repo_dir = Path(__file__).resolve().parent
    source = repo_dir / "skill" / "make-ppt"
    integrations_dir = repo_dir / "integrations"
    registry = load_registry(integrations_dir / "clients.json")
    args = parse_args(registry)

    if not (source / "SKILL.md").is_file():
        raise FileNotFoundError(f"Canonical skill not found: {source}")

    client_ids = tuple(registry) if args.client == "all" else (args.client,)
    specs = tuple(registry[client_id] for client_id in client_ids)
    project_dir = args.project_dir.resolve()

    if args.install_python_deps:
        install_python_dependencies(
            source / "requirements.txt",
            dry_run=args.dry_run,
        )

    jobs = [(spec, skill_target(spec, args.scope, project_dir)) for spec in specs]
    unique_targets: list[Path] = []
    for _, target in jobs:
        if target not in unique_targets:
            unique_targets.append(target)

    existing = [
        target for target in unique_targets if target.exists() or target.is_symlink()
    ]
    if existing and not args.force and not args.dry_run:
        formatted = "\n".join(f"  - {target}" for target in existing)
        raise FileExistsError(
            "Installation stopped before making changes because these targets exist:\n"
            f"{formatted}\nRerun with --force to replace them."
        )

    for spec, target in jobs:
        print(f"{spec.client_id:12} -> {target}")

    for target in unique_targets:
        install_skill(source, target, force=args.force, dry_run=args.dry_run)

    for spec, target in jobs:
        apply_skill_metadata(spec, integrations_dir, target, dry_run=args.dry_run)
        sync_agents(
            spec,
            source,
            integrations_dir,
            args.scope,
            project_dir,
            dry_run=args.dry_run,
        )

    handle_legacy_installations(
        specs,
        args.scope,
        project_dir,
        migrate=args.migrate_legacy,
        dry_run=args.dry_run,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
