#!/usr/bin/env python3
"""Install the canonical make-ppt Agent Skill into supported AI clients."""

from __future__ import annotations

import argparse
import shutil
from pathlib import Path


CLIENTS = ("codex", "claude", "kiro", "copilot")
CLAUDE_AGENT_SPECS = {
    "ppt-planner": "ppt-planner-role.md",
    "ppt-builder": "ppt-builder-role.md",
}
GENERATED_MARKER = (
    "<!-- Generated by make-ppt/install.py. "
    "Edit the canonical role or Claude integration template, then reinstall. -->"
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Install make-ppt into Agent Skills compatible AI clients."
    )
    parser.add_argument(
        "--client",
        choices=(*CLIENTS, "all"),
        default="all",
        help="Client to install for (default: all).",
    )
    parser.add_argument(
        "--scope",
        choices=("user", "project"),
        default="user",
        help="Install globally for the user or into one project (default: user).",
    )
    parser.add_argument(
        "--project-dir",
        type=Path,
        default=Path.cwd(),
        help="Project root for --scope project (default: current directory).",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Replace an existing make-ppt installation.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print target paths without writing files.",
    )
    return parser.parse_args()


def user_target(client: str) -> Path:
    roots = {
        "codex": Path.home() / ".agents" / "skills",
        "claude": Path.home() / ".claude" / "skills",
        "kiro": Path.home() / ".kiro" / "skills",
        "copilot": Path.home() / ".copilot" / "skills",
    }
    return roots[client] / "make-ppt"


def project_target(client: str, project_dir: Path) -> Path:
    roots = {
        "codex": project_dir / ".agents" / "skills",
        "claude": project_dir / ".claude" / "skills",
        "kiro": project_dir / ".kiro" / "skills",
        "copilot": project_dir / ".github" / "skills",
    }
    return roots[client] / "make-ppt"


def claude_agents_dir(scope: str, project_dir: Path) -> Path:
    if scope == "user":
        return Path.home() / ".claude" / "agents"
    return project_dir / ".claude" / "agents"


def safe_to_replace(target: Path) -> bool:
    return target.name == "make-ppt" and target.parent.name == "skills"


def render_claude_agent(frontmatter: Path, role: Path) -> str:
    frontmatter_text = frontmatter.read_text(encoding="utf-8").strip()
    role_text = role.read_text(encoding="utf-8").strip()
    if frontmatter_text.startswith("---") or frontmatter_text.endswith("---"):
        raise ValueError(
            f"Claude frontmatter template must not include delimiters: {frontmatter}"
        )
    return (
        f"---\n{frontmatter_text}\n---\n\n"
        f"{GENERATED_MARKER}\n\n{role_text}\n"
    )


def write_text_atomic(target: Path, content: str) -> None:
    target.parent.mkdir(parents=True, exist_ok=True)
    temporary = target.with_name(f".{target.name}.tmp")
    try:
        temporary.write_text(content, encoding="utf-8", newline="\n")
        temporary.replace(target)
    finally:
        if temporary.exists():
            temporary.unlink()


def sync_claude_agents(
    skill_source: Path,
    integration_dir: Path,
    target_dir: Path,
    *,
    dry_run: bool,
) -> None:
    for agent_name, role_name in CLAUDE_AGENT_SPECS.items():
        target = target_dir / f"{agent_name}.md"
        print(f"claude-agent -> {target}")
        if dry_run:
            continue

        frontmatter = integration_dir / f"{agent_name}.yaml"
        role = skill_source / "references" / role_name
        if not frontmatter.is_file():
            raise FileNotFoundError(f"Claude agent template not found: {frontmatter}")
        if not role.is_file():
            raise FileNotFoundError(f"Canonical role not found: {role}")
        write_text_atomic(target, render_claude_agent(frontmatter, role))


def install_one(
    client: str,
    source: Path,
    codex_metadata: Path,
    target: Path,
    *,
    force: bool,
    dry_run: bool,
) -> None:
    print(f"{client:7} -> {target}")
    if dry_run:
        return

    if target.exists() or target.is_symlink():
        if not force:
            raise FileExistsError(
                f"{target} already exists; rerun with --force to replace it."
            )
        if not safe_to_replace(target):
            raise RuntimeError(f"Refusing to replace unexpected target: {target}")
        if target.is_dir() and not target.is_symlink():
            shutil.rmtree(target)
        else:
            target.unlink()

    target.parent.mkdir(parents=True, exist_ok=True)
    shutil.copytree(
        source,
        target,
        ignore=shutil.ignore_patterns("__pycache__", "*.pyc", ".DS_Store"),
    )

    if client == "codex" and codex_metadata.exists():
        metadata_target = target / "agents" / "openai.yaml"
        metadata_target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(codex_metadata, metadata_target)


def main() -> int:
    args = parse_args()
    repo_dir = Path(__file__).resolve().parent
    source = repo_dir / "skill" / "make-ppt"
    codex_metadata = repo_dir / "integrations" / "codex" / "openai.yaml"
    claude_integration_dir = repo_dir / "integrations" / "claude"

    if not (source / "SKILL.md").is_file():
        raise FileNotFoundError(f"Canonical skill not found: {source}")

    clients = CLIENTS if args.client == "all" else (args.client,)
    project_dir = args.project_dir.resolve()

    jobs = []
    for client in clients:
        target = (
            user_target(client)
            if args.scope == "user"
            else project_target(client, project_dir)
        )
        jobs.append((client, target))

    existing = [
        target for _, target in jobs if target.exists() or target.is_symlink()
    ]
    if existing and not args.force and not args.dry_run:
        formatted = "\n".join(f"  - {target}" for target in existing)
        raise FileExistsError(
            "Installation stopped before making changes because these targets exist:\n"
            f"{formatted}\nRerun with --force to replace them."
        )

    for client, target in jobs:
        install_one(
            client,
            source,
            codex_metadata,
            target,
            force=args.force,
            dry_run=args.dry_run,
        )
        if client == "claude":
            sync_claude_agents(
                source,
                claude_integration_dir,
                claude_agents_dir(args.scope, project_dir),
                dry_run=args.dry_run,
            )

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
