from __future__ import annotations

import subprocess
import sys
import tempfile
import tomllib
import unittest
from pathlib import Path

from client_registry import agent_target, load_registry, skill_target


REPO_DIR = Path(__file__).resolve().parents[1]
INSTALLER = REPO_DIR / "install.py"
SKILL_SOURCE = REPO_DIR / "skill" / "make-ppt"
BASH_ENTRYPOINTS = (
    "skill/make-ppt/scripts/run_python.sh",
    "skill/make-ppt/scripts/render_pptx.sh",
)


def run_installer(project_dir: Path, *args: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [
            sys.executable,
            str(INSTALLER),
            "--scope",
            "project",
            "--project-dir",
            str(project_dir),
            *args,
        ],
        check=True,
        capture_output=True,
        text=True,
    )


class InstallTests(unittest.TestCase):
    def test_bash_entrypoints_are_tracked_as_executable(self) -> None:
        for relative_path in BASH_ENTRYPOINTS:
            tracked = subprocess.run(
                ["git", "ls-files", "--stage", "--", relative_path],
                cwd=REPO_DIR,
                check=True,
                capture_output=True,
                text=True,
            ).stdout
            mode = tracked.split(maxsplit=1)[0]
            self.assertEqual("100755", mode, relative_path)

    def test_claude_install_generates_agents_from_canonical_roles(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            project_dir = Path(temporary)
            run_installer(project_dir, "--client", "claude")

            self.assertTrue(
                (
                    project_dir
                    / ".claude"
                    / "skills"
                    / "make-ppt"
                    / "scripts"
                    / "render_ppt_mac.applescript"
                ).is_file()
            )

            for agent_name, role_name in (
                ("ppt-planner", "ppt-planner-role.md"),
                ("ppt-builder", "ppt-builder-role.md"),
            ):
                generated = (
                    project_dir / ".claude" / "agents" / f"{agent_name}.md"
                ).read_text(encoding="utf-8")
                role = (SKILL_SOURCE / "references" / role_name).read_text(
                    encoding="utf-8"
                ).strip()

                self.assertIn(f"name: {agent_name}", generated)
                self.assertIn("model: inherit", generated)
                self.assertIn("Generated by make-ppt/install.py", generated)
                self.assertTrue(generated.endswith(f"{role}\n"))

    def test_reinstall_refreshes_legacy_or_drifted_agents(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            project_dir = Path(temporary)
            agents_dir = project_dir / ".claude" / "agents"
            agents_dir.mkdir(parents=True)
            builder = agents_dir / "ppt-builder.md"
            builder.write_text("---\nmodel: sonnet\n---\nlegacy\n", encoding="utf-8")

            run_installer(project_dir, "--client", "claude")
            first_install = builder.read_text(encoding="utf-8")
            self.assertIn("model: inherit", first_install)
            self.assertNotIn("model: sonnet", first_install)

            builder.write_text("manual drift\n", encoding="utf-8")
            run_installer(project_dir, "--client", "claude", "--force")
            refreshed = builder.read_text(encoding="utf-8")
            self.assertIn("Generated by make-ppt/install.py", refreshed)
            self.assertNotIn("manual drift", refreshed)

    def test_all_clients_install_role_agents_to_native_agent_directories(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            project_dir = Path(temporary)
            run_installer(project_dir, "--client", "all")
            registry = load_registry(REPO_DIR / "integrations" / "clients.json")

            for spec in registry.values():
                self.assertTrue(
                    (skill_target(spec, "project", project_dir) / "SKILL.md").is_file(),
                    spec.client_id,
                )
                for agent_name in ("ppt-planner", "ppt-builder"):
                    self.assertTrue(
                        agent_target(
                            spec, agent_name, "project", project_dir
                        ).is_file(),
                        f"{spec.client_id}:{agent_name}",
                    )

            expected = {
                ".claude/agents/ppt-planner.md": "name: ppt-planner",
                ".claude/agents/ppt-builder.md": "name: ppt-builder",
                ".codex/agents/ppt-planner.toml": 'name = "ppt-planner"',
                ".codex/agents/ppt-builder.toml": 'name = "ppt-builder"',
                ".kiro/agents/ppt-planner.md": "name: ppt-planner",
                ".kiro/agents/ppt-builder.md": "name: ppt-builder",
                ".github/agents/ppt-planner.agent.md": "description: Compare narrative",
                ".github/agents/ppt-builder.agent.md": "description: Implement an approved",
                ".agents/agents/ppt-planner/agent.md": "name: ppt-planner",
                ".agents/agents/ppt-builder/agent.md": "name: ppt-builder",
            }
            for relative_path, marker in expected.items():
                generated = (project_dir / relative_path).read_text(encoding="utf-8")
                self.assertIn(marker, generated, relative_path)

            for relative_path, role_name in (
                (".kiro/agents/ppt-planner.md", "ppt-planner-role.md"),
                (".kiro/agents/ppt-builder.md", "ppt-builder-role.md"),
                (".github/agents/ppt-planner.agent.md", "ppt-planner-role.md"),
                (".github/agents/ppt-builder.agent.md", "ppt-builder-role.md"),
                (".agents/agents/ppt-planner/agent.md", "ppt-planner-role.md"),
                (".agents/agents/ppt-builder/agent.md", "ppt-builder-role.md"),
            ):
                generated = (project_dir / relative_path).read_text(encoding="utf-8")
                role = (SKILL_SOURCE / "references" / role_name).read_text(
                    encoding="utf-8"
                ).strip()
                self.assertTrue(generated.endswith(f"{role}\n"), relative_path)

            planner_toml = tomllib.loads(
                (project_dir / ".codex/agents/ppt-planner.toml").read_text(
                    encoding="utf-8"
                )
            )
            planner_role = (SKILL_SOURCE / "references" / "ppt-planner-role.md").read_text(
                encoding="utf-8"
            ).strip()
            self.assertEqual(planner_role, planner_toml["developer_instructions"])

            self.assertIn(
                "ppt-planner.toml",
                run_installer(project_dir, "--client", "all", "--dry-run").stdout,
            )

    def test_dry_run_reports_agents_without_writing(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            project_dir = Path(temporary)
            result = run_installer(project_dir, "--client", "claude", "--dry-run")

            self.assertIn("ppt-planner.md", result.stdout)
            self.assertIn("ppt-builder.md", result.stdout)
            self.assertFalse((project_dir / ".claude").exists())

    def test_registry_drives_client_paths_and_includes_antigravity(self) -> None:
        registry = load_registry(REPO_DIR / "integrations" / "clients.json")
        self.assertTrue(
            {"codex", "claude", "kiro", "copilot", "antigravity"}.issubset(
                registry
            )
        )
        with tempfile.TemporaryDirectory() as temporary:
            project_dir = Path(temporary)
            antigravity = registry["antigravity"]
            self.assertEqual(
                project_dir / ".agents" / "skills" / "make-ppt",
                skill_target(antigravity, "project", project_dir),
            )
            self.assertEqual(
                project_dir / ".agents" / "agents" / "ppt-planner" / "agent.md",
                agent_target(antigravity, "ppt-planner", "project", project_dir),
            )
        for spec in registry.values():
            if spec.agent_format == "markdown":
                for agent_name in ("ppt-planner", "ppt-builder"):
                    self.assertTrue(
                        (
                            REPO_DIR
                            / "integrations"
                            / spec.integration_dir
                            / f"{agent_name}.yaml"
                        ).is_file(),
                        f"missing {spec.client_id} template for {agent_name}",
                    )

    def test_legacy_installation_is_backed_up_only_when_requested(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            project_dir = Path(temporary)
            legacy = project_dir / ".codex" / "skills" / "make-ppt"
            legacy.mkdir(parents=True)
            (legacy / "SKILL.md").write_text("legacy\n", encoding="utf-8")

            warning = run_installer(
                project_dir, "--client", "codex", "--dry-run"
            ).stdout
            self.assertIn("legacy skill found", warning)
            self.assertTrue(legacy.is_dir())

            run_installer(
                project_dir, "--client", "codex", "--migrate-legacy"
            )
            self.assertFalse(legacy.exists())
            backups = list(legacy.parent.glob("make-ppt.legacy-*"))
            self.assertEqual(1, len(backups))
            self.assertEqual(
                "legacy\n",
                (backups[0] / "SKILL.md").read_text(encoding="utf-8"),
            )

    def test_dependency_install_option_is_explicit_and_dry_runnable(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            project_dir = Path(temporary)
            result = run_installer(
                project_dir,
                "--client",
                "antigravity",
                "--install-python-deps",
                "--dry-run",
            )
            self.assertIn("python-deps ->", result.stdout)
            self.assertIn("requirements.txt", result.stdout)


if __name__ == "__main__":
    unittest.main()
