from __future__ import annotations

import subprocess
import sys
import tempfile
import unittest
from pathlib import Path


REPO_DIR = Path(__file__).resolve().parents[1]
INSTALLER = REPO_DIR / "install.py"
SKILL_SOURCE = REPO_DIR / "skill" / "make-ppt"


def run_installer(project_dir: Path, *args: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [
            sys.executable,
            str(INSTALLER),
            "--scope",
            "project",
            "--project-dir",
            str(project_dir),
            *args,
        ],
        check=True,
        capture_output=True,
        text=True,
    )


class InstallTests(unittest.TestCase):
    def test_claude_install_generates_agents_from_canonical_roles(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            project_dir = Path(temporary)
            run_installer(project_dir, "--client", "claude")

            for agent_name, role_name in (
                ("ppt-planner", "ppt-planner-role.md"),
                ("ppt-builder", "ppt-builder-role.md"),
            ):
                generated = (
                    project_dir / ".claude" / "agents" / f"{agent_name}.md"
                ).read_text(encoding="utf-8")
                role = (SKILL_SOURCE / "references" / role_name).read_text(
                    encoding="utf-8"
                ).strip()

                self.assertIn(f"name: {agent_name}", generated)
                self.assertIn("model: inherit", generated)
                self.assertIn("Generated by make-ppt/install.py", generated)
                self.assertTrue(generated.endswith(f"{role}\n"))

    def test_reinstall_refreshes_legacy_or_drifted_agents(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            project_dir = Path(temporary)
            agents_dir = project_dir / ".claude" / "agents"
            agents_dir.mkdir(parents=True)
            builder = agents_dir / "ppt-builder.md"
            builder.write_text("---\nmodel: sonnet\n---\nlegacy\n", encoding="utf-8")

            run_installer(project_dir, "--client", "claude")
            first_install = builder.read_text(encoding="utf-8")
            self.assertIn("model: inherit", first_install)
            self.assertNotIn("model: sonnet", first_install)

            builder.write_text("manual drift\n", encoding="utf-8")
            run_installer(project_dir, "--client", "claude", "--force")
            refreshed = builder.read_text(encoding="utf-8")
            self.assertIn("Generated by make-ppt/install.py", refreshed)
            self.assertNotIn("manual drift", refreshed)

    def test_non_claude_install_does_not_generate_claude_agents(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            project_dir = Path(temporary)
            run_installer(project_dir, "--client", "kiro")

            self.assertFalse((project_dir / ".claude" / "agents").exists())

    def test_dry_run_reports_agents_without_writing(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            project_dir = Path(temporary)
            result = run_installer(project_dir, "--client", "claude", "--dry-run")

            self.assertIn("ppt-planner.md", result.stdout)
            self.assertIn("ppt-builder.md", result.stdout)
            self.assertFalse((project_dir / ".claude").exists())


if __name__ == "__main__":
    unittest.main()
